# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/zeeofficial01/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

**Unit of analysis:** One row represents one report date for one pseudonymized client and one pseudonymized content item.

**Time window:** I use March 2026 (`2026-03-01` through `2026-03-31`) as the mid-panel development and verification month.
## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [1]:
from google.colab import userdata
from huggingface_hub import hf_hub_download
import pandas as pd

# Load token from Colab Secrets
HF_TOKEN = userdata.get("HF_TOKEN")

print("HF_TOKEN loaded:", HF_TOKEN is not None)

# Download the March 2026 partition
file_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance/month=2026-03/data_0.parquet",
    repo_type="dataset",
    token=HF_TOKEN
)

# Read March data
march = pd.read_parquet(file_path)

print("Shape:", march.shape)
print("\nColumns:")
print(march.columns.tolist())

print("\nFirst 5 rows:")
display(march.head())

HF_TOKEN loaded: True
Shape: (9841378, 30)

Columns:
['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

First 5 rows:

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20,0,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125,1,616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7,0,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11,0,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
march = pd.read_parquet(file_path)

print("Shape:", march.shape)

print("\nColumns:")
print(march.columns.tolist())

print("\nFirst 5 rows:")
display(march.head())

Shape: (9841378, 30)

Columns:
['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

First 5 rows:

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,None,20,0,67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,None,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,None,125,1,616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,None,7,0,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,None,11,0,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

### Field contract

**Features**

* `gsc_impressions`
* `gsc_clicks`
* `gsc_avg_position`
* `ga4_sessions`
* `scroll_events`

**Label / proxy**

* A future-performance proxy will be constructed from the daily performance history. The label is not a stored column in the March 2026 table.

**Context**

* `report_date`
* `client_hash_id`
* `content_hash_id`
* `client_has_gsc`
* `client_has_ga4`
* `gsc_data_available`
* `ga4_data_available`

**Excluded**

* `gsc_sum_position` — excluded because `gsc_avg_position` already represents the ranking signal.
* `ga4_pageviews`, `ga4_users`, `ga4_engaged_sessions`, `ga4_total_engagement_sec` — excluded to keep the first feature frame small.
* Traffic-source and individual AI-referral fields — excluded to keep the first five-feature frame within the assignment limit.

In [3]:
print("March columns:")
for i, col in enumerate(march.columns, 1):
    print(i, col)

March columns:
1 report_date
2 client_hash_id
3 content_hash_id
4 client_has_gsc
5 client_has_ga4
6 gsc_data_available
7 ga4_data_available
8 gsc_impressions
9 gsc_clicks
10 gsc_sum_position
11 gsc_avg_position
12 ga4_pageviews
13 ga4_sessions
14 ga4_users
15 ga4_engaged_sessions
16 ga4_total_engagement_sec
17 sessions_organic
18 sessions_direct
19 sessions_referral
20 sessions_social
21 sessions_paid
22 sessions_ai
23 ai_chatgpt
24 ai_perplexity
25 ai_gemini
26 ai_copilot
27 ai_claude
28 ai_meta
29 ai_other
30 scroll_events

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [4]:
# Verification Query 1: Grain

grain_check = march.groupby(
    ["report_date", "client_hash_id", "content_hash_id"]
).size()

print("Total rows:", len(march))
print("Unique date-client-content combinations:", grain_check.size)
print("Maximum rows per combination:", grain_check.max())

Total rows: 9841378
Unique date-client-content combinations: 9841378
Maximum rows per combination: 1

In [5]:
# Verification Query 2: row count and date span

print("Row count:", len(march))
print("Minimum report date:", march["report_date"].min())
print("Maximum report date:", march["report_date"].max())

Row count: 9841378
Minimum report date: 2026-03-01
Maximum report date: 2026-03-31

In [6]:
# Verification Query 3: GSC availability using IS TRUE

available = march[march["gsc_data_available"].eq(True)]

print("Rows where gsc_data_available IS TRUE:", len(available))
print("Total March rows:", len(march))
print("Share available:", len(available) / len(march))

Rows where gsc_data_available IS TRUE: 3611061
Total March rows: 9841378
Share available: 0.36692635929643186

In [7]:
# Load April 2026 for the future outcome window

april_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance/month=2026-04/data_0.parquet",
    repo_type="dataset",
    token=HF_TOKEN
)

april = pd.read_parquet(april_path)

print("April shape:", april.shape)
print("April dates:", april["report_date"].min(), "to", april["report_date"].max())

April shape: (10424730, 30)
April dates: 2026-04-01 to 2026-04-30

In [8]:
# Build a simple future-performance proxy from April

future = (
    april.groupby(["client_hash_id", "content_hash_id"], as_index=False)
    .agg(
        future_impressions=("gsc_impressions", "sum"),
        future_clicks=("gsc_clicks", "sum")
    )
)

print("Future outcome rows:", len(future))
display(future.head())

Future outcome rows: 362172

,client_hash_id,content_hash_id,future_impressions,future_clicks
0,client_06d356715a8ff3b6,content_0059a4d4195810c9,873,2
1,client_06d356715a8ff3b6,content_005b6b7f7b8dda7f,634,1
2,client_06d356715a8ff3b6,content_0153b7dedc3fc40d,640,2
3,client_06d356715a8ff3b6,content_0241f6a890063db0,85,1
4,client_06d356715a8ff3b6,content_045f673b3d3c18a4,153,2

In [9]:
# Create the future-performance label
# 1 = declining, 0 = not declining

future["is_declining_label"] = (
    future["future_impressions"] == 0
).astype(int)

print("Label distribution:")
print(future["is_declining_label"].value_counts())

Label distribution:
is_declining_label
0    194760
1    167412
Name: count, dtype: int64

### Data limits

This March 2026 slice has an unbalanced history, so not every client or content item has the same amount of historical data. GSC and GA4 availability also differs across rows, so a metric being missing does not necessarily mean zero performance. This slice can show observed content-performance signals, but it cannot by itself establish causality or tell us what would have happened under a different decision.
## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

In [10]:
# Five-feature frame for March 2026

features = march[
    [
        "gsc_impressions",
        "gsc_clicks",
        "gsc_avg_position",
        "ga4_sessions",
        "scroll_events",
    ]
].copy()

print("Feature frame shape:", features.shape)

display(features.head())

Feature frame shape: (9841378, 5)

   gsc_impressions  gsc_clicks  gsc_avg_position  ga4_sessions  scroll_events
0               20           0          3.350000           NaN            NaN
1                1           0          0.000000           NaN            NaN
2              125           1          4.928000           NaN            NaN
3                7           0          4.000000           NaN            NaN
4               11           0          2.272727           NaN            NaN

### Five features — available when?

* `gsc_impressions` — knowable at the decision moment because it comes from the observed GSC performance available for that report date.
* `gsc_clicks` — knowable at the decision moment because it comes from the observed GSC performance available for that report date.
* `gsc_avg_position` — knowable at the decision moment because it is an observed GSC ranking signal for that report date.
* `ga4_sessions` — knowable at the decision moment when GA4 data is available for that row.
* `scroll_events` — knowable at the decision moment when the corresponding GA4 event data is available for that row.

In [ ]:
# Build the future outcome from April 2026

april_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance/month=2026-04/data_0.parquet",
    repo_type="dataset",
    token=HF_TOKEN
)

april = pd.read_parquet(april_path)

print("April shape:", april.shape)
print("April dates:", april["report_date"].min(), "to", april["report_date"].max())

# Future performance proxy
future = (
    april.groupby(
        ["client_hash_id", "content_hash_id"],
        as_index=False
    )
    .agg(
        future_impressions=("gsc_impressions", "sum"),
        future_clicks=("gsc_clicks", "sum")
    )
)

# 1 = declining, 0 = not declining
future["is_declining_label"] = (
    future["future_impressions"] == 0
).astype(int)

print("Future outcome rows:", len(future))
print("Label distribution:")
print(future["is_declining_label"].value_counts())

### Deliberate leakage experiment

In [ ]:
from google.colab import userdata
from huggingface_hub import hf_hub_download
import pandas as pd

HF_TOKEN = userdata.get("HF_TOKEN")

file_path = hf_hub_download(
    repo_id="FlyRank/internship-warehouse",
    filename="fact_content_daily_performance/month=2026-03/data_0.parquet",
    repo_type="dataset",
    token=HF_TOKEN
)

march = pd.read_parquet(file_path)

print("March shape:", march.shape)

In [ ]:
# Deliberate leakage experiment
# Intentionally bring the future label into the March feature data.

leaky_features = march[
    [
        "client_hash_id",
        "content_hash_id",
        "gsc_impressions",
        "gsc_clicks",
        "gsc_avg_position",
        "ga4_sessions",
        "scroll_events",
    ]
].merge(
    future[
        [
            "client_hash_id",
            "content_hash_id",
            "is_declining_label",
        ]
    ],
    on=["client_hash_id", "content_hash_id"],
    how="inner"
)

print("Leaky feature frame shape:", leaky_features.shape)
print("Leakage column added:", "is_declining_label" in leaky_features.columns)

display(leaky_features.head())

### Leakage lesson

The `is_declining_label` column was deliberately added to the feature frame even though it is derived from future April performance. This is leakage because the label would not be available at the March decision moment. The experiment shows why future outcome information must not be used as an input feature.

The leakage column is removed from the final feature set.

In [ ]:
# Remove the deliberately leaked future label.
honest_features = leaky_features.drop(
    columns=["is_declining_label"]
)

print("Final honest feature columns:")
print(honest_features.columns.tolist())

print("Final feature count:", len(honest_features.columns))

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.